In [173]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.linear_model import RidgeCV, LinearRegression, LassoCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures

In [174]:
df = pd.read_csv("data.csv")

In [175]:
for index, columns in enumerate(["A", "B", "C", "D"]):
    for i in range(0,3):
        fill_value = df[columns].iloc[i]
        df[f"{columns}_Lag_{i}"] = df[columns].shift(-i)
df.drop(["A","B","C","D"],axis=1,inplace=True)
df = df.dropna()

In [176]:
df

A_Lag_0  A_Lag_1  A_Lag_2  B_Lag_0  B_Lag_1  B_Lag_2  C_Lag_0  C_Lag_1  \
0      10.07    10.00     9.95     2.18     2.20     2.21      3.0      3.0   
1      10.00     9.95     9.93     2.20     2.21     2.30      3.0      3.0   
2       9.95     9.93     9.88     2.21     2.30     2.30      3.0      2.5   
3       9.93     9.88     9.84     2.30     2.30     2.31      2.5      2.5   
4       9.88     9.84     9.78     2.30     2.31     2.80      2.5      2.5   
..       ...      ...      ...      ...      ...      ...      ...      ...   
221     9.08     9.04     8.98     2.80     2.90     3.00      0.0      0.0   
222     9.04     8.98     8.91     2.90     3.00     3.10      0.0      0.0   
223     8.98     8.91     8.80     3.00     3.10     3.20      0.0      0.0   
224     8.91     8.80     8.73     3.10     3.20     3.10      0.0      0.0   
225     8.80     8.73     8.70     3.20     3.10     3.00      0.0      0.0   

     C_Lag_2  D_Lag_0  D_Lag_1  D_Lag_2  
0        3.0      0.8      0.7      0.9  
1        2.5      0.7      0.9      1.1  
2        2.5      0.9      1.1      0.9  
3        2.5      1.1      0.9      0.9  
4        2.5      0.9      0.9      1.0  
..       ...      ...      ...      ...  
221      0.0      1.3      1.3      1.5  
222      0.0      1.3      1.5      1.6  
223      0.0      1.5      1.6      1.4  
224      0.0      1.6      1.4      1.5  
225      0.0      1.4      1.5      1.3  

[226 rows x 12 columns]

In [177]:
pca = PCA(n_components=12,svd_solver = 'full')

In [178]:
pca.fit(df)

PCA(n_components=12, svd_solver='full')

In [179]:
newData = pd.DataFrame(pca.fit_transform(df))

In [180]:
newData

0         1         2         3         4         5         6   \
0   -1.227631 -0.656025  0.699172 -2.461488  0.176375 -0.065515  0.006764   
1   -1.201132 -0.776071  0.634726 -2.137925  0.122962 -0.186821  0.015271   
2   -1.147146 -0.903071  0.600218 -1.848445  0.171147  0.080592  0.072106   
3   -1.071541 -1.071157  0.654802 -1.618966  0.199812  0.153886 -0.009901   
4   -1.291042 -1.277926  0.772290 -1.621021 -0.161494  0.024626 -0.191015   
..        ...       ...       ...       ...       ...       ...       ...   
221 -0.380796 -3.296495  1.304376  2.457737 -0.042521 -0.006521 -0.001720   
222 -0.587577 -3.340315  1.218018  2.592798 -0.071015 -0.067300 -0.005440   
223 -0.779059 -3.388884  1.244607  2.694048 -0.028743  0.212050 -0.016876   
224 -0.885952 -3.366591  1.319128  2.780628  0.106967  0.187827  0.071065   
225 -0.859859 -3.311663  1.517388  2.778740  0.259555  0.158264 -0.020772   

           7         8         9         10        11  
0   -0.024978  0.094239 -0.012084 -0.014883  0.012331  
1   -0.411841 -0.084659 -0.193633 -0.003052  0.006681  
2   -0.325432 -0.193261  0.233808 -0.000070 -0.016335  
3    0.014362  0.065598 -0.005176  0.009030  0.006218  
4   -0.089579  0.022024  0.003244  0.020573 -0.007884  
..        ...       ...       ...       ...       ...  
221 -0.070489  0.082561 -0.013230  0.037626 -0.007836  
222 -0.076027 -0.038587 -0.000510  0.019369 -0.007728  
223 -0.013753 -0.112515  0.013371 -0.010882 -0.022287  
224 -0.012263  0.127477 -0.016719 -0.016248  0.018426  
225  0.015633 -0.112019  0.007368  0.042734  0.008178  

[226 rows x 12 columns]

In [181]:
df.var(axis=0).sort_values(ascending=False)

B_Lag_2    3.767377
B_Lag_1    3.759014
B_Lag_0    3.749038
C_Lag_2    2.154163
C_Lag_1    2.143738
C_Lag_0    2.132960
A_Lag_2    1.631581
A_Lag_1    1.628678
A_Lag_0    1.626211
D_Lag_0    0.903024
D_Lag_1    0.899449
D_Lag_2    0.895569
dtype: float64

In [182]:
len(df)

226

In [183]:
print(f"Total Variance for normal data: {pd.Series(df.var(axis=0)).sum()}")

Total Variance for normal data: 25.290800631268446


In [184]:
newData.var(axis=0).sort_values(ascending=False)

0     14.383806
1      7.879041
2      1.623026
3      1.054869
4      0.182813
5      0.064759
6      0.046335
7      0.022541
8      0.017885
9      0.011830
10     0.003179
11     0.000715
dtype: float64

In [185]:
print(f"Total Variance for PCA data: {newData.var(axis=0).sum()}")

Total Variance for PCA data: 25.290800631268425


# PCA Calculation

### Steps
1. Centre Matrix
2. Calculate the covariance matrix
3. Calculate eigenvectors & eigenvalues of the covariance matrix
4. Select the first n eigenvectors


In [186]:
mean_df = np.mean(df.T,axis=1)

In [188]:
centre =df - mean_df

In [190]:
covariance = np.cov(df.T)

In [211]:
centre

A_Lag_0   A_Lag_1   A_Lag_2   B_Lag_0   B_Lag_1   B_Lag_2   C_Lag_0  \
0    0.459956  0.395885  0.351637  0.761903  0.777832  0.784292  1.089159   
1    0.389956  0.345885  0.331637  0.781903  0.787832  0.874292  1.089159   
2    0.339956  0.325885  0.281637  0.791903  0.877832  0.874292  1.089159   
3    0.319956  0.275885  0.241637  0.881903  0.877832  0.884292  0.589159   
4    0.269956  0.235885  0.181637  0.881903  0.887832  1.374292  0.589159   
..        ...       ...       ...       ...       ...       ...       ...   
221 -0.530044 -0.564115 -0.618363  1.381903  1.477832  1.574292 -1.910841   
222 -0.570044 -0.624115 -0.688363  1.481903  1.577832  1.674292 -1.910841   
223 -0.630044 -0.694115 -0.798363  1.581903  1.677832  1.774292 -1.910841   
224 -0.700044 -0.804115 -0.868363  1.681903  1.777832  1.674292 -1.910841   
225 -0.810044 -0.874115 -0.898363  1.781903  1.677832  1.574292 -1.910841   

      C_Lag_1   C_Lag_2   D_Lag_0   D_Lag_1   D_Lag_2  
0    1.102434  1.115708 -0.923009 -1.026106 -0.828761  
1    1.102434  0.615708 -1.023009 -0.826106 -0.628761  
2    0.602434  0.615708 -0.823009 -0.626106 -0.828761  
3    0.602434  0.615708 -0.623009 -0.826106 -0.828761  
4    0.602434  0.615708 -0.823009 -0.826106 -0.728761  
..        ...       ...       ...       ...       ...  
221 -1.897566 -1.884292 -0.423009 -0.426106 -0.228761  
222 -1.897566 -1.884292 -0.423009 -0.226106 -0.128761  
223 -1.897566 -1.884292 -0.223009 -0.126106 -0.328761  
224 -1.897566 -1.884292 -0.123009 -0.326106 -0.228761  
225 -1.897566 -1.884292 -0.323009 -0.226106 -0.428761  

[226 rows x 12 columns]

In [210]:
covariance

array([[ 1.62621111,  1.62365182,  1.61600052, -0.70366747, -0.59132321,
        -0.4729127 , -1.46284048, -1.46289323, -1.45821264, -0.60886324,
        -0.62102338, -0.62838794],
       [ 1.62365182,  1.62867766,  1.62634454, -0.8174348 , -0.71177918,
        -0.59906359, -1.45204925, -1.45767216, -1.45780396, -0.58826844,
        -0.60608568, -0.61724332],
       [ 1.61600052,  1.62634454,  1.63158086, -0.9211178 , -0.82551021,
        -0.7194675 , -1.4355844 , -1.446364  , -1.45206361, -0.56400216,
        -0.5857304 , -0.6025527 ],
       [-0.70366747, -0.8174348 , -0.9211178 ,  3.7490377 ,  3.66632681,
         3.5460438 ,  0.7791985 ,  0.89258424,  0.99625887,  0.34987953,
         0.462001  ,  0.55647274],
       [-0.59132321, -0.71177918, -0.82551021,  3.66632681,  3.7590135 ,
         3.6754729 ,  0.6362075 ,  0.76128086,  0.87472088,  0.22917656,
         0.35132537,  0.46227959],
       [-0.4729127 , -0.59906359, -0.7194675 ,  3.5460438 ,  3.6754729 ,
         3.76737661,  

In [191]:
eigenvalues,eigenvectors = np.linalg.eig(covariance)

In [192]:
idx = eigenvalues.argsort()[::-1]

In [193]:
eigenvalues = eigenvalues[idx]

In [194]:
eigenvectors = eigenvectors[:,idx]

In [197]:
principals = eigenvectors.T.dot(centre.T)

In [206]:
principals.T[:,0:4]

array([[-1.22763053e+00, -6.56024796e-01, -6.99172092e-01,
        -2.46148814e+00],
       [-1.20113195e+00, -7.76071214e-01, -6.34725750e-01,
        -2.13792456e+00],
       [-1.14714566e+00, -9.03070511e-01, -6.00218079e-01,
        -1.84844478e+00],
       [-1.07154136e+00, -1.07115711e+00, -6.54801707e-01,
        -1.61896572e+00],
       [-1.29104227e+00, -1.27792595e+00, -7.72290306e-01,
        -1.62102093e+00],
       [-1.59911169e+00, -1.46857994e+00, -7.25355377e-01,
        -1.52572624e+00],
       [-1.96765635e+00, -1.65740979e+00, -6.14608896e-01,
        -1.37817577e+00],
       [-2.43669559e+00, -1.99882132e+00, -5.57402619e-01,
        -1.27529968e+00],
       [-3.09345945e+00, -2.17933373e+00, -3.89514312e-01,
        -1.31829901e+00],
       [-3.77403418e+00, -2.30565775e+00, -1.49587946e-01,
        -1.29648496e+00],
       [-4.18774288e+00, -2.14151332e+00,  7.85558162e-02,
        -1.25580992e+00],
       [-4.50939712e+00, -2.07045173e+00,  1.89625664e-01,
      

In [207]:
pca.explained_variance_ratio_

array([5.68736688e-01, 3.11537818e-01, 6.41745536e-02, 4.17096124e-02,
       7.22845122e-03, 2.56056790e-03, 1.83209835e-03, 8.91286505e-04,
       7.07181105e-04, 4.67760895e-04, 1.25698662e-04, 2.82831321e-05])

In [209]:
pca.components_

array([[ 2.43426023e-01,  2.52958202e-01,  2.61071915e-01,
        -4.18565016e-01, -4.05471640e-01, -3.83866013e-01,
        -2.85326051e-01, -2.97125465e-01, -3.06658471e-01,
        -1.27483259e-01, -1.39533705e-01, -1.48945574e-01],
       [-2.49564838e-01, -2.29473337e-01, -2.09155338e-01,
        -3.77570178e-01, -4.15958842e-01, -4.43712786e-01,
         3.15545628e-01,  2.97664534e-01,  2.79379891e-01,
         1.60457641e-01,  1.44090215e-01,  1.26950397e-01],
       [-3.21418371e-01, -3.35425506e-01, -3.50260164e-01,
        -6.21423915e-02, -1.64369251e-02,  3.77382330e-02,
        -4.40770878e-02, -5.03329529e-02, -5.07507329e-02,
        -4.69703196e-01, -4.72455535e-01, -4.52829545e-01],
       [-3.28339042e-01, -3.23330570e-01, -3.16047089e-01,
         3.49906713e-02, -6.56422947e-03, -5.02035495e-02,
        -3.88233018e-01, -3.93938627e-01, -3.97382144e-01,
         2.64062684e-01,  2.77361509e-01,  2.71097079e-01],
       [-8.77454117e-03,  8.22898291e-03,  3.8026115